COUNTRIES = [
["Россия", "Russia", "Russian cuisine"],
["Китай", "China", "Chinese cuisine"],
["Грузия", "Georgia", "Georgian cuisine"],
["Италия", "Italy", "Italian cuisine"],
["Япония", "Japan", "Japanese cuisine"],
["Таиланд", "Thailand", "Thai cuisine"],
["Индия", "India", "Indian cuisine"],
["Мексика", "Mexico", "Mexican cuisine"],
["Греция", "Greece", "Greek cuisine"],
["Узбекистан", "Uzbekistan", "Uzbek cuisine"],
["Франция", "France", "French cuisine"],
["Испания", "Spain", "Spanish cuisine"],
["Турция", "Turkey", "Turkish cuisine"],
["Корея", "Korea", "Korean cuisine"],
["Вьетнам", "Vietnam", "Vietnamese cuisine"],
["Марокко", "Morocco", "Moroccan cuisine"],
["Ливан", "Lebanon", "Lebanese cuisine"],
["Перу", "Peru", "Peruvian cuisine"],
["Аргентина", "Argentina", "Argentine cuisine"],
["США", "United States", "American cuisine"],
["Германия", "Germany", "German cuisine"],
["Австрия", "Austria", "Austrian cuisine"],
["Венгрия", "Hungary", "Hungarian cuisine"],
["Португалия", "Portugal", "Portuguese cuisine"],
["Бразилия", "Brazil", "Brazilian cuisine"],
["Индонезия", "Indonesia", "Indonesian cuisine"],
["Малайзия", "Malaysia", "Malaysian cuisine"],
["Филиппины", "Philippines", "Filipino cuisine"],
["Египет", "Egypt", "Egyptian cuisine"],
["Эфиопия", "Ethiopia", "Ethiopian cuisine"],
["Польша", "Poland", "Polish cuisine"],
["Чехия", "Czech Republic", "Czech cuisine"],
["Украина", "Ukraine", "Ukrainian cuisine"],
["Армения", "Armenia", "Armenian cuisine"],
["Азербайджан", "Azerbaijan", "Azerbaijani cuisine"],
["Казахстан", "Kazakhstan", "Kazakh cuisine"],
["Иран", "Iran", "Iranian cuisine"],
["Израиль", "Israel", "Israeli cuisine"],
["Швеция", "Sweden", "Swedish cuisine"],
["Норвегия", "Norway", "Norwegian cuisine"],
["Дания", "Denmark", "Danish cuisine"],
["Нидерланды", "Netherlands", "Dutch cuisine"],
["Бельгия", "Belgium", "Belgian cuisine"],
["Швейцария", "Switzerland", "Swiss cuisine"],
["Великобритания", "United Kingdom", "British cuisine"],
["Ирландия", "Ireland", "Irish cuisine"],
["Ямайка", "Jamaica", "Jamaican cuisine"],
["Куба", "Cuba", "Cuban cuisine"],
["Ирак", "Iraq", "Iraqi cuisine"],
["Саудовская Аравия", "Saudi Arabia", "Saudi Arabian cuisine"],
]
