name: Test
'on': [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=@vkusno_test_kitchen&text=Токен из сейфа работает!"
